// generated by go run genicons.go; DO NOT EDIT

// Package mdiMapsLunchDining provides the (Base) lunch_dining icon
package mdiMapsLunchDining

var Ivg = []byte{
	0x89, 0x49, 0x56, 0x47, 0x02, 0x0a, 0x00, 0x50, 0x50, 0xb0, 0xb0}
